
name: Package Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install Packages
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        python -m pip install -r requirements.txt
    
    - name: Package Application
      shell: bash
      run: pyinstaller --clean -y bot_runner.spec

    - name: Add Necessary Resources
      run: |
        cp -r ./BotResources/ ./dist/BotResources

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: CoWorkingBot-Linux
        path: dist/
        retention-days: 15


  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install Packages
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        python -m pip install -r requirements.txt
    
    - name: Package Application
      shell: bash
      run: pyinstaller --clean -y bot_runner.spec

    - name: Add Necessary Resources
      run: |
        cp -r ./BotResources/ ./dist/BotResources

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: CoWorkingBot-Windows
        path: dist/
        retention-days: 15


  build-mac:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: setup python 3.9.13
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.13

    - name: Install Packages
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        python -m pip install -r requirements.txt
    
    - name: Package Application
      shell: bash
      run: pyinstaller --clean -y -n "CoWorkingBot" --windowed --onefile --add-data="BotResources:BotResources" bot_runner.py

    - name: Add Necessary Resources
      run: |
        cp -r ./BotResources/ ./dist/BotResources

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: CoWorkingBot-MacOS
        path: dist/
        retention-days: 15